---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-forwarder
  namespace: chris-streaming
  labels:
    app: event-forwarder
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: event-forwarder
  template:
    metadata:
      labels:
        app: event-forwarder
    spec:
      serviceAccountName: event-forwarder
      containers:
        - name: event-forwarder
          image: localhost:5005/fnndsc/compute-event-forwarder:dev
          imagePullPolicy: Always
          env:
            - name: COMPUTE_ENV
              value: kubernetes
            - name: K8S_NAMESPACE
              value: chris-streaming
            - name: K8S_LABEL_SELECTOR
              value: "chrisproject.org/role=plugininstance"
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: STREAM_STATUS_BASE
              value: stream:job-status
            - name: STREAM_NUM_SHARDS
              value: "8"
            - name: EMIT_INITIAL_STATE
              value: "true"
