---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-consumer
  namespace: chris-streaming
  labels:
    app: status-consumer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: status-consumer
  template:
    metadata:
      labels:
        app: status-consumer
    spec:
      containers:
        - name: status-consumer
          image: localhost:5005/fnndsc/compute-status-consumer:dev
          imagePullPolicy: Always
          env:
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: STREAM_STATUS_BASE
              value: stream:job-status
            - name: STREAM_STATUS_DLQ
              value: stream:job-status-dlq
            - name: STREAM_NUM_SHARDS
              value: "8"
            - name: STATUS_CONSUMER_GROUP
              value: status-consumer-group
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: HANDLER_RETRIES
              value: "3"
