---
apiVersion: v1
kind: Service
metadata:
  name: quickwit
  namespace: chris-streaming
  labels:
    app: quickwit
spec:
  selector:
    app: quickwit
  ports:
    - name: http
      port: 7280
      targetPort: 7280
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quickwit
  namespace: chris-streaming
  labels:
    app: quickwit
spec:
  serviceName: quickwit
  replicas: 1
  selector:
    matchLabels:
      app: quickwit
  template:
    metadata:
      labels:
        app: quickwit
    spec:
      containers:
        - name: quickwit
          image: quickwit/quickwit:latest
          args: ["run"]
          env:
            - name: QW_METASTORE_URI
              value: "file:///quickwit/qwdata/metastore"
            - name: QW_DEFAULT_INDEX_ROOT_URI
              value: "file:///quickwit/qwdata/indexes"
          ports:
            - containerPort: 7280
          volumeMounts:
            - name: data
              mountPath: /quickwit/qwdata
          readinessProbe:
            httpGet:
              path: /health/livez
              port: 7280
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: 7280
            initialDelaySeconds: 30
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
