FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml ./
RUN pip install --no-cache-dir ".[log-consumer]"

COPY chris_streaming/ chris_streaming/

CMD ["python", "-m", "chris_streaming.log_consumer"]
