---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storebase-pvc
  namespace: chris-streaming
  labels:
    app: pfcon
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
