KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_event-forwarder="event-forwarder-secret"
    user_log-producer="log-producer-secret"
    user_status-consumer="status-consumer-secret"
    user_log-consumer="log-consumer-secret";
};
